using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xceed.Words.NET;
using System.Diagnostics;

namespace lab_11_microsoft_word
{
    class Program
    {
        static void Main(string[] args)
        {
            var document = DocX.Create("MyReport.docx");
            document.InsertParagraph("This is an amazing report");
            document.InsertParagraph($"Report generated by <<author>> {DateTime.Now}");
            document.Save();
            Process.Start("WINWORD.EXE", "MyReport.docx");
            //Timer with a report
            //Create wpf application
            //Big button "Go"
            //"Go" pressed
            //Create a folder, in the folder creates 100 text files
            //On the rerun should delete
            //Datetime take time
            //Put time on the screen
            //Generate microsft report
        }
    }
}
